FROM mambaorg/micromamba:1.4.7

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN apt update && apt -y install git gcc g++ make curl ca-certificates && \
    curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts --install-dir=/opt && \
    ln -s /opt/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud

# Use micromamba to resolve conda-forge, much faster than conda
RUN micromamba install -y python=3.10.12 pip=23.2.1 rdkit=2023.03.3 -c conda-forge
RUN pip install \
    bcrypt==4.3.0 \
    "celery[gevent,amqp,redis]"==5.6.2 \
    epam.indigo==1.4.3 \
    "fastapi[standard]"==0.121.3 \
    fastapi-mcp==0.4.0 \
    hdbscan==0.8.33 \
    networkx==2.6.3 \
    pandas==1.5.3 \
    "passlib[bcrypt]"==1.7.4 \
    pillow==10.1.0 \
    protobuf==3.19.0 \
    pulp==2.6.0 \
    pydantic==2.12.4 \
    pymongo==4.4.1 \
    pytest==7.4.1 \
    "python-jose[cryptography]"==3.3.0 \
    python-multipart==0.0.20 \
    pyyaml==6.0.1 \
    requests==2.31.0 \
    scikit-learn==1.0.2 \
    scipy==1.7.3 \
    svgutils==0.3.4 \
    tqdm==4.66.1 \
    uvicorn==0.38.0 \
    google-auth==2.29.0 \
    python-keycloak==3.7.0 \
    rdchiral==1.1.0

COPY . /ASKCOSv2/askcos2_core
WORKDIR /ASKCOSv2/askcos2_core

CMD ["python", "app.py"]
